# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
#
#
# TODO (mark)
# - [ ] site info
# - [ ] any useful pages
# - [ ] add categories and tags to posts
# - [ ] remove other header junk, not necessary really
title: Computationally Thinking
email:
description: >- # this means to ignore newlines until "baseurl:"
  explain( world | science, data, computation, experience)
#twitter_username: compthink
github_username: rateldajer
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

analytics:
  provider: "google-gtag"
  google:
    #tracking_id: "UA-31267662-1"
    tracking_id: "G-P1S2TJ5V9L"
    anonymize_ip: false # default

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Computationally Thinking"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Mark Crowley (he/him)<br><br>Assoc. Professor in AI at the Univ. of Waterloo<br/><br/>My Thoughts on <i>Artificial Intelligence, Ethics, Technology, Science,</i> and <i>Society</i><br>Opinions are my own, and no one else's.<br/><br/>"
      #      <tt>Never Cruel or Cowardly, Never Give Up, Never Give In.</tt>
  links:
    - label: "Research Website"
      icon: "fas fa-fw fa-link"
      url: "https://markcrowley.ca"
    - label: "Bluesky"
      icon: "fab fa-fw fa-bluesky"
      url: "https://bsky.app/profile/compthink.bsky.social"
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "https://sigmoid.social/@compthink"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/markanthonycrowley/"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-link"
      url: "https://github.com/rateldajer"

footer:
  links:
    - label: "Bluesky"
      icon: "fab fa-fw fa-bluesky"
      url: "https://bsky.app/profile/compthink.bsky.social"
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "https://sigmoid.social/@compthink"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/markanthonycrowley/"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-link"
      url: "https://github.com/rateldajer"




defaults:
  # _posts
  - 
    scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      #classes: wide # note this will remove the toc and make text wider
      author_profile: true
      read_time: true
      show_date: true
      comments: false
      share: true
      related: true
      toc: false #maybe turn this off?
      show_tags: true
    #header:
      #image: /assets/conferences/wurzburgpalace_small.jpg
  - 
    scope:
      path: ""
      type: drafts
    values:
      published: false
  -
    scope:
      path: "_drafts"
    values:
      type: drafts
      published: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      show_date: true
      comments: false
      share: true
      related: true
      toc: true #maybe turn this off?
      show_tags: true

# category_archive:
#   type: liquid
#   path: /categories/
tag_archive:
  type: liquid
  path: /tags/


